
name: '[push] [main] Build'
on:
  push:
    branches:
      - main
    tags-ignore: '**'
    paths:
      - 'tbcpkg/**'
      - 'tests/**'
      - 'tbc.nim'
      - 'tbc.nimble'
      - 'nimble.lock'
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Cache nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('nimble.lock') }}
          restore-keys: |
            ${{ runner.os }}-nimble-
      
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable

      - name: install dependencies
        run: nimble install -y -d

      - name: check
        run: nimble check

      - name: setup
        run: nimble setup
      
      - name: build
        run: nimble build

      - name: test
        run: nim test
