
name: '[push] [main] Build'
on:
  push:
    branches:
      - main
    tags-ignore: '**'
    paths:
      - 'tbcpkg/**'
      - 'tests/**'
      - 'tbc.nim'
      - 'tbc.nimble'
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable

      - name: refresh
        run: nimble refresh

      - name: check
        run: nimble check

      - name: build
        run: nimble build

      - name: test
        run: |
          nimble tester
          bin/tester
